name: tf-apply
on:
  push:
    branches: [ "main", "master" ]
    paths:
      - '**/*.tf'
      - '.github/workflows/tf-apply.yaml'
  workflow_dispatch: {}

permissions:
  contents: read

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  TF_CLI_ARGS_init: "-input=false"
  TF_CLI_ARGS_apply: "-input=false -auto-approve"
  TF_LOG: "ERROR"
  TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
  TF_VAR_region: ${{ secrets.GCP_REGION }}

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init -upgrade
      - name: Terraform Apply
        run: terraform apply -auto-approve
      - name: Show outputs
        run: terraform output -json | jq .
